name: app_multinivel
description: Aplicaci칩n Flutter para red de referidos y c치lculo de comisiones multinivel.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.27.0

  # Firebase Auth
  firebase_auth: ^4.17.4
  intl: ^0.19.0
  # Cloud Firestore
  cloud_firestore: ^4.17.3
  nimble_charts: ^0.5.0-beta
  # Para usar controladores de texto, navegaci칩n y dise침o
  cupertino_icons: ^1.0.6
  http: ^0.13.6
  lottie: ^2.7.0
  fl_chart: ^0.65.0
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/animations/ic_launcher_round.png"
    web:
      generate: true
      image_path: "assets/animations/ic_launcher_round.png"
flutter:
  uses-material-design: true
  assets:
    - assets/animations/login.json
    - assets/animations/logo.webp
    - assets/animations/logo.gif
