// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBVrK2pdPeQ33ppvWftUZ9U0ZSDytdpAw',
    appId: '1:559817737819:web:f7fdf4181b2bde1425a17e',
    messagingSenderId: '559817737819',
    projectId: 'appcomisiones-2eff7',
    authDomain: 'appcomisiones-2eff7.firebaseapp.com',
    storageBucket: 'appcomisiones-2eff7.firebasestorage.app',
    measurementId: 'G-6NL13LV8XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLNpcPAfuRErP6UWzmRsXF3Pf7-NSDdsg',
    appId: '1:559817737819:android:a3c6f865ad2daaca25a17e',
    messagingSenderId: '559817737819',
    projectId: 'appcomisiones-2eff7',
    storageBucket: 'appcomisiones-2eff7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE5TDhxcs1zxHsxhVsVGbVVyDo2yLGLp0',
    appId: '1:559817737819:ios:4b327c1b6758e39025a17e',
    messagingSenderId: '559817737819',
    projectId: 'appcomisiones-2eff7',
    storageBucket: 'appcomisiones-2eff7.firebasestorage.app',
    iosBundleId: 'com.example.appComisiones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE5TDhxcs1zxHsxhVsVGbVVyDo2yLGLp0',
    appId: '1:559817737819:ios:4b327c1b6758e39025a17e',
    messagingSenderId: '559817737819',
    projectId: 'appcomisiones-2eff7',
    storageBucket: 'appcomisiones-2eff7.firebasestorage.app',
    iosBundleId: 'com.example.appComisiones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBVrK2pdPeQ33ppvWftUZ9U0ZSDytdpAw',
    appId: '1:559817737819:web:9e04c95d0292436c25a17e',
    messagingSenderId: '559817737819',
    projectId: 'appcomisiones-2eff7',
    authDomain: 'appcomisiones-2eff7.firebaseapp.com',
    storageBucket: 'appcomisiones-2eff7.firebasestorage.app',
    measurementId: 'G-RJGG9V03J2',
  );
}
